Repository kowainik/validation-selective, pull requests merged in 2020-03, with the labels that each got.

#5 [#1] Cleanup repo
  .travis.yml
  README.md
  appveyor.yml
  stack-8.4.4.yaml
  stack-8.6.5.yaml
  stack.yaml
Labels: refactoring

#10 [#3] Bring tests
  .travis.yml
  stack.yaml
  test/Spec.hs
  test/Test/Property.hs
  validation-selective.cabal
Labels: tests

#12 [#4] Implement Selective instance
  README.md
  src/Validation.hs
  stack.yaml
  validation-selective.cabal
Labels: enhancement

#15 [#9] Setup doctests
  .github/workflows/ci.yml
  .travis.yml
  appveyor.yml
  src/Validation.hs
  test/Doctest.hs
  validation-selective.cabal
Labels: tests

#17 [#13] Add laws property-tests for the Selective instance
  test/Test/Gen.hs
  test/Test/Property.hs
  validation-selective.cabal
Labels: tests

#18 [#11] Write custom efficient implementation of all typeclass methods
  src/Validation.hs
  test/Test/Gen.hs
  test/Test/Property.hs
Labels: enhancement, tests

#19 [#14] Derive NFData instance
  src/Validation.hs
  test/Doctest.hs
  validation-selective.cabal
Labels: enhancement

#21 [#8] Add more interface functions
  src/Validation.hs
Labels: enhancement

#26 [#22] partitionValidations property test
  test/Spec.hs
  test/Test/Gen.hs
  test/Test/Laws.hs
  test/Test/Properties.hs
  validation-selective.cabal
Labels: tests

#27 [#20] Add Data instance
  src/Validation.hs
Labels: enhancement

#23 [#7] Improve Haddock documentation
  src/Validation.hs
  test/Doctest.hs
Labels: documentation, enhancement, tests

#30 [#28] Rewrite Selective instance example
  src/Validation.hs
Labels: documentation

#29 [#25] Introduce some combinators to work with 'Validation (NonEmpty e)'
  src/Validation.hs
Labels: enhancement

#33 [#32] Improve Either-Validation documentation
  src/Validation.hs
Labels: documentation

#31 [#16] Write readme
  README.md
  src/Validation.hs
  validation-selective.cabal
Labels: documentation

#37 [#36] Typeclasses table
  README.md
  src/Validation.hs
Labels: documentation

#38 [#34] Support GHC-8.8.3
  .github/workflows/ci.yml
  .travis.yml
  stack.yaml
  validation-selective.cabal
Labels: enhancement, refactoring
