Repository kowainik/validation-selective, pull requests merged in 2020-05, with the labels that each got.

#44 Use new GitHub Actions for Haskell
  .github/workflows/ci.yml
Labels: CI

#45 [#24] Extra interface functions
  CHANGELOG.md
  src/Validation.hs
  src/Validation.hs-boot
  src/Validation/Combinators.hs
  test/Doctest.hs
  validation-selective.cabal
Labels: enhancement

#46 Prepare 0.1.0.0 release
  CHANGELOG.md
  src/Validation.hs
  src/Validation/Combinators.hs
  validation-selective.cabal
Labels: documentation
